import type { BattleContent, CardDefinition, CardId } from '../game/types'

const cards = {
  guiding_edge: {
    id: 'guiding_edge',
    name: '引锋式',
    cost: 1,
    kind: '剑式',
    description: '造成 80% 攻势伤害，获得 2 点剑意。',
    effectId: 'damage_and_sword_intent',
    powerPercent: 80,
    swordIntent: 2,
  },
  hidden_edge: {
    id: 'hidden_edge',
    name: '藏锋',
    cost: 1,
    kind: '心法',
    description: '获得 22 点护盾；下一次获得剑意时额外获得 1 点。',
    effectId: 'shield_and_prime_intent',
    shield: 22,
  },
  returning_wind: {
    id: 'returning_wind',
    name: '回风剑',
    cost: 2,
    kind: '剑式',
    description: '连续攻击 2 次，每次造成 70% 攻势伤害。',
    effectId: 'double_hit',
    powerPercent: 70,
    hits: 2,
  },
  armor_piercing_star: {
    id: 'armor_piercing_star',
    name: '破甲点星',
    cost: 2,
    kind: '剑式',
    description: '造成 90% 攻势伤害，施加 2 层破甲。',
    effectId: 'damage_and_armor_break',
    powerPercent: 90,
    armorBreak: 2,
  },
  ten_thousand_blades: {
    id: 'ten_thousand_blades',
    name: '万剑成势',
    cost: 4,
    kind: '剑式',
    description: '按当前剑意攻击，每段造成 45% 攻势伤害，不消耗剑意。',
    effectId: 'sword_intent_multihit',
    powerPercent: 45,
  },
  mountain_splitter: {
    id: 'mountain_splitter',
    name: '一剑开山',
    cost: 5,
    kind: '剑式',
    description: '造成 160% 攻势伤害，每点剑意再提高 45%，随后消耗全部剑意。',
    effectId: 'consume_sword_intent_finisher',
    powerPercent: 160,
  },
} satisfies Record<CardId, CardDefinition>

export const M1_CONTENT = {
  leader: {
    id: 'leader',
    name: '无名修士',
    title: '青岚剑 · 太虚藏锋诀',
    maxHp: 180,
    attack: 24,
    defense: 18,
    attackIntervalMs: 2_000,
  },
  spirits: [
    {
      id: 'blade_tail_fox',
      name: '刃尾狐',
      title: '三式追击',
      maxHp: 92,
      attack: 16,
      defense: 10,
      attackIntervalMs: 4_500,
    },
    {
      id: 'iron_beak_crane',
      name: '铁喙鹤',
      title: '重击破甲',
      maxHp: 104,
      attack: 20,
      defense: 14,
      attackIntervalMs: 5_500,
    },
  ],
  enemy: {
    id: 'clay_idol',
    name: '泥胎傀',
    title: '槐阴古道 · 高护体',
    maxHp: 320,
    attack: 21,
    defense: 32,
    attackIntervalMs: 3_000,
  },
  cards,
  startingDeck: Object.keys(cards) as CardId[],
} satisfies BattleContent
